import java.util.Random;

/*
	ISYS 320
	Name(s):
	Date: 
*/

/*
1. Predict the minimum possible value and maximum possible values that
could be assigned to each of the variables based on the values that can 
be generated by the call to the nextInt method of the Random class

	| VARIABLE	| MIN VALUE	| MAX VALUE	| 
	| a	 		|	1		|		100	|			
	| b			|	20		|		600	|		
	| c			|	20		|		70	|	
	| d			|	80		|		100	|
	| e			|		4	|		40	|				
*/
public class P3_RandomRanges {

	public static void main(String[] args) {
		// this program does nothing observable, the statements are copied here
		// for your convenience
		Random rand = new Random();
		
		int a = rand.nextInt( 100 );
		int b = rand.nextInt( 20 ) + 30;
		int c = rand.nextInt( 20 + 50 );
		int d = rand.nextInt( 100 ) - 20;
		int e = rand.nextInt( 10 ) * 4;
	}

}
